# _config.yml
url: https://tss-web.secodis.com
logo: "/assets/img/logo1.png"
avatar: "/assets/img/logo1.png"
title: TSS-WEB 
description: An open security requirement framework for web-based applications and services.
author: Matthias Rohr
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
repository: "Secodis/TSS-WEB"
enable_copy_code_button: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
search: true
#lunr:
#  search_within_pages: true
#  search_full_content: true
search_provider: google
google:
  search_engine_id: 75489f1b156bd4879
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: 
  
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Secodis/TSS-WEB/"
  
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
      sidebar: toc
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :

TITLE_GENERAL_REQUIREMENTS: "Types of Requirements"
URL_GENERAL_REQUIREMENTS: /General/Requirements

TITLE_GENERAL_TERMS: "Terms"
URL_GENERAL_TERMS: /General/Terms

TITLE_GENERAL_ROLES: "Roles"
URL_GENERAL_ROLES: /General/Roles

TITLE_GENERAL_RISKCLASSES: "Risk Classes"
URL_GENERAL_RISKCLASSES: /General/RiskClasses

TITLE_GENERAL_FAQ: "FAQ"
URL_GENERAL_FAQ: /General/FAQ

TITLE_GENERAL_LICENSE: "License"
URL_GENERAL_LICENSE: /licenses/by/4.0/deed.en

TITLE_SSDLC_CONTROLS: "Part A: SSDLC Controls"
URL_SSDLC_CONTROLS: /#part-a-ssdlc-controls

TITLE_SSDLC_SECENV: "A.1 - Secure Dev Environment"
URL_SSDLC_SECENV: /Controls/SSDLC_Secure-Dev-Environment

TITLE_SSDLC_SECENV_ACCESS: "A.1.1 Securing Access to the Development Environment"
URL_SSDLC_SECENV_ACCESS: /Controls/SSDLC_Secure-Dev-Environment

TITLE_SSDLC_SECENV_CODEPROTECT: "A.1.2 Protection of Source and Program Code"
URL_SSDLC_SECENV_CODEPROTECT: /Controls/SSDLC_Secure-Dev-Environment

TITLE_SSDLC_SECENV_CODEPROTECT: "A.1.2 Protection of Source and Program Code"
URL_SSDLC_SECENV_CODEPROTECT: /Controls/SSDLC_Secure-Dev-Environment

TITLE_SSDLC_SECDEV: "A.2 - Secure Development Process"
URL_SSDLC_SECDEV: /Controls/SSDLC_Secure-Development

TITLE_SSDLC_SECDEV_ROLES: "A.2.1  Roles & Training"
URL_SSDLC_SECDEV_ROLES: /Controls/SSDLC_Secure-Development#a21-roles--training

TITLE_SSDLC_SECDEV_SECDESIGN: "A.2.2 Secure By Design"
URL_SSDLC_SECDEV_SECDESIGN: /Controls/SSDLC_Secure-Development#a22-secure-by-design

TITLE_SSDLC_SECDEV_AGILESEC: "A.2.3 Security Evaluation of New Features"
URL_SSDLC_SECDEV_AGILESEC: /Controls/SSDLC_Secure-Development#a23-security-evaluation-of-new-features

TITLE_SSDLC_SECDEV_SECIMP: "A.2.4 Secure Implementation"
URL_SSDLC_SECDEV_SECIMP: /Controls/SSDLC_Secure-Development#a24-secure-implementation

TITLE_SSDLC_SECDEV_BUILD: "A.2.5 Secure Build & Deployment"
URL_SSDLC_SECDEV_BUILD: /Controls/SSDLC_Secure-Development#a25-secure-build--deployment

TITLE_SSDLC_SECDEV_3RDPARTY: "A.2.6 Security of Third-Party Dependencies"
URL_SSDLC_SECDEV_3RDPARTY: /Controls/SSDLC_Secure-Development#a26-security-of-third-party-dependencies

TITLE_SSDLC_SECDEV_SECGATES: "A.2.7 Security Approvals (Security Gates)"
URL_SSDLC_SECDEV_SECGATES: /Controls/SSDLC_Secure-Development#a27-security-approvals-security-gates

TITLE_SSDLC_SECDEV_VULMREM: "A.2.8 Remediation of Security Findings"
URL_SSDLC_SECDEV_VULMREM: /Controls/SSDLC_Secure-Development#a28-remediation-of-security-findings

TITLE_SSDLC_SECDEV_SECDOCU: "A.2.9 Security Documentation"
URL_SSDLC_SECDEV_SECDOCU: /Controls/SSDLC_Secure-Development#a29-security-documentation

TITLE_SSDLC_SECTESTS: "A.3 - Security Tests"
URL_SSDLC_SECTESTS: /Controls/SSDLC_Security-Tests

TITLE_SSDLC_OUTDEV: "A.4 - Outsourced Development"
URL_SSDLC_OUTDEV: /Controls/SSDLC_Outsourced-Development

TITLE_SSDLC_SECOP: "A.5 - Secure Operation"
URL_SSDLC_SECOP: /Controls/SSDLC_Secure-Operation

TITLE_IMPL_CONTROLS: "Part B: Secure Implementation Controls"
URL_IMPL_CONTROLS: /#part-b-secure-implementation-controls

TITLE_IMPL_PRINCIPLES: "B.1 - Secure Design Principles"
URL_IMPL_PRINCIPLES: /Controls/SecImpl_Secure-Design-Principles

TITLE_IMPL_INPUTVAL: "B.2 - Input Validation"
URL_IMPL_INPUTVAL: /Controls/SecImpl_InputVal

TITLE_IMPL_FILEUPLOADS: "B.3 - Secure Fileuploads and Downloads"
URL_IMPL_FILEUPLOADS: /Controls/SecImpl_FileUploads

TITLE_IMPL_OUTPUTVAL: "B.4 - Output Validation & Encoding"
URL_IMPL_OUTPUTVAL: /Controls/SecImpl_OutputVal

TITLE_IMPL_USERAUTH: "B.5 - Secure User Registration & Authentication"
URL_IMPL_USERAUTH: /Controls/SecImpl_UserAuth

TITLE_IMPL_USERPASSWD: "B.6 - User Passwords"
URL_IMPL_USERPASSWD: /Controls/SecImpl_User-Passwords

TITLE_IMPL_SESSIONMGMT: "B.7 - Secure Session Management"
URL_IMPL_SESSIONMGMT: /Controls/SecImpl_SessionMgmt

TITLE_IMPL_AUTHZ: "B.8 - Authorization"
URL_IMPL_AUTHZ: /Controls/SecImpl_Access-Control

TITLE_IMPL_ERRORLOG: "B.9 - Error Handling and Logging"
URL_IMPL_ERRORLOG: /Controls/SecImpl_Error-Handling-and-Logging

TITLE_IMPL_CRYPTO: "B.10 - Data Security"
URL_IMPL_CRYPTO: /Controls/SecImpl_Data-Security

TITLE_IMPL_SECRETS: "B.11 - Protection of Secrets"
URL_IMPL_SECRETS: /Controls/SecImpl_Secrets

TITLE_IMPL_APISEC: "B.12 - API Security"
URL_IMPL_APISEC: /Controls/SecImpl_API-Security

TITLE_IMPL_CLIENTSEC: "B.13 - Client-Side Security"
URL_IMPL_CLIENTSEC: /Controls/SecImpl_Client-Side-Security

TITLE_IMPL_HTTPHEADERSEC: "B.14 - HTTP Header Security"
URL_IMPL_HTTPHEADERSEC: /Controls/SecImpl_HTTP-Header-Security

TITLE_MATERIAL_TOPTENMAPPING: "OWASP Top Ten Mapping"
URL_MATERIAL_TOPTENMAPPING: /Material/OWASP_Top_Ten_Mapping

TITLE_MATERIAL_SAMMMAPPING: "OWASP SAMM Mapping (Draft)"
URL_MATERIAL_SAMMMAPPING: /Material/OWASP_SAMM-2.0-Mapping

TITLE_MATERIAL_MSSDLMAPPING: "MS SDL Mapping"
URL_MATERIAL_MSSDLMAPPING: /Material/Microsoft_SDL_Mapping

        
