# _config.yml
logo: "/assets/img/logo1.png"
avatar: "/assets/img/logo1.png"
title: TSS-WEB 
description: An open security requirement framework for web-based applications and services.
author: Matthias Rohr
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#show_downloads: false
#google_analytics:
#theme: jekyll-theme-minimal

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

TITLE_GENERAL_REQUIREMENTS: "Types of Requirements"
URL_GENERAL_REQUIREMENTS: https://tss-web.secodis.com/General/Requirements

TITLE_GENERAL_TERMS: "Terms"
URL_GENERAL_TERMS: https://tss-web.secodis.com/General/Terms

TITLE_GENERAL_ROLES: "Roles"
URL_GENERAL_ROLES: https://tss-web.secodis.com/General/Roles

TITLE_GENERAL_ASSURANCECLASSES: "Assurance Classes"
URL_GENERAL_ASSURANCECLASSES: https://tss-web.secodis.com/General/AssuranceClasses

TITLE_SSDLC_SECENV: "A.1 - Secure Dev Environment"
URL_SSDLC_SECENV: https://tss-web.secodis.com/Controls/Secure-Dev-Environment

TITLE_SSDLC_SDLC: "A.2 - Security within SDLC"
URL_SSDLC_SDLC: https://tss-web.secodis.com/Controls/Security-wthin-SDLC

TITLE_SSDLC_SECTESTS: "A.3 - Security Tests"
URL_SSDLC_SECTESTS: https://tss-web.secodis.com/Controls/Security-Tests

TITLE_SSDLC_SECOP: "A.4 - Secure Operation"
URL_SSDLC_SECOP: https://tss-web.secodis.com/Controls/Secure-Operation

TITLE_SSDLC_OUTDEV: "A.5 - Outsourced Development"
URL_SSDLC_OUTDEV: https://tss-web.secodis.com/Controls/Outsourced-Development

TITLE_SSDLC_REMEDIATION: "A.6 - Vulnerability Remediation in Production"
URL_SSDLC_REMEDIATION: https://tss-web.secodis.com/Controls/Vulnerability-Remediation

TITLE_IMPL_PRINCIPLES: "B.1 - Secure Design Principles"
URL_IMPL_PRINCIPLES: https://tss-web.secodis.com/Controls/SecImpl_Secure-Design-Principles

TITLE_IMPL_INPUTVAL: "B.2 - Input Validation"
URL_IMPL_INPUTVAL: https://tss-web.secodis.com/Controls/SecImpl_InputVal

TITLE_IMPL_FILEUPLOADS: "B.3 - Secure Fileuploads and Downloads"
URL_IMPL_FILEUPLOADS: https://tss-web.secodis.com/Controls/SecImpl_FileUploads

TITLE_IMPL_OUTPUTVAL: "B.4 - Output Validation"
URL_IMPL_OUTPUTVAL: https://tss-web.secodis.com/Controls/SecImpl_OutputVal

TITLE_IMPL_USERAUTH: "B.5 - Secure User Registration & Authentication"
URL_IMPL_USERAUTH: https://tss-web.secodis.com/Controls/SecImpl_UserAuth

TITLE_IMPL_USERPASSWD: "B.6 - User Passwords"
URL_IMPL_USERPASSWD: https://tss-web.secodis.com/Controls/SecImpl_User-Passwords

TITLE_IMPL_SESSIONMGMT: "B.7 - Secure Session Management"
URL_IMPL_SESSIONMGMT: https://tss-web.secodis.com/Controls/SecImpl_SessionMgmt

TITLE_IMPL_AUTHZ: "B.8 - Authorization"
URL_IMPL_AUTHZ: https://tss-web.secodis.com/Controls/SecImpl_Access-Control

TITLE_IMPL_ERRORLOG: "B.9 - Error Handling and Logging"
URL_IMPL_ERRORLOG: https://tss-web.secodis.com/Controls/SecImpl_Error-Handling-and-Logging

TITLE_IMPL_CRYPTO: "B.10 - Data Security"
URL_IMPL_CRYPTO: https://tss-web.secodis.com/Controls/SecImpl_Data-Security

TITLE_IMPL_SECRETS: "B.11 - Protection of Secrets"
URL_IMPL_SECRETS: https://tss-web.secodis.com/Controls/SecImpl_Secrets

TITLE_IMPL_APISEC: "B.12 - API Security"
URL_IMPL_APISEC: https://tss-web.secodis.com/Controls/SecImpl_API-Security

TITLE_IMPL_CLIENTSEC: "B.13 - Client-Side Security"
URL_IMPL_CLIENTSEC: https://tss-web.secodis.com/Controls/SecImpl_Client-Side-Security

TITLE_IMPL_HTTPHEADERSEC: "B.14 - HTTP Header Security"
URL_IMPL_HTTPHEADERSEC: https://tss-web.secodis.com/Controls/SecImpl_HTTP-Header-Security

TITLE_MATERIAL_TOPTENMAPPING: "OWASP Top Ten Mapping"
URL_MATERIAL_TOPTENMAPPING: https://tss-web.secodis.com/D_Material/OWASP_Top_Ten_Mapping

TITLE_MATERIAL_SAMMMAPPING: "OWASP SAMM Mapping (Draft)"
URL_MATERIAL_SAMMMAPPING: https://tss-web.secodis.com/D_Material/OWASP_SAMM-2.0-Mapping


defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
