# _config.yml
URL_SSDLC_REMEDIATION: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/01_Vulnerability-Remediation
URL_SSDLC_SECOP: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/02_Secure-Operation
URL_SSDLC_SECENV: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/03_Secure-Dev-Environment
URL_SSDLC_SDLC: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/04_Security-wthin-SDLC
URL_SSDLC_SECTESTS: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/05_Security-Tests
URL_SSDLC_OUTDEV: https://secodis.github.io/TSS-WEB/B_SSDLC_Requirements/06_Outsourced-Development

URL_GENERAL_DEFINITIONS: https://secodis.github.io/TSS-WEB/A_General/Definitions
URL_GENERAL_AC: https://secodis.github.io/TSS-WEB/A_General/Definitions#assurance-classes
URL_GENERAL_TERMS: https://secodis.github.io/TSS-WEB/A_General/Definitions#terms
URL_GENERAL_ROLES: https://secodis.github.io/TSS-WEB/A_General/Definitions#roles

URL_IMPL_PRINCIPLES: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/01_Secure-Design-Principles
URL_IMPL_INPUTVAL: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/02_InputVal
URL_IMPL_FILEUPLOADS: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/03_FileUploads
URL_IMPL_OUTPUTVAL: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/04_OutputVal
URL_IMPL_USERAUTH: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/05_UserAuth
URL_IMPL_USERPASSWD: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/06_User-Passwords
URL_IMPL_SESSIONMGMT: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/07_Session-Mgmt
URL_IMPL_AUTHZ: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/08_Access-Control
URL_IMPL_ERRORLOG: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/09_Error-Handling-And-Logging
URL_IMPL_CRYPTO: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/10_Data-Security
URL_IMPL_SECRETS: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/11_Secrets
URL_IMPL_CLIENTSEC: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/12_Client-Side-Security
URL_IMPL_APISEC: https://secodis.github.io/TSS-WEB/C_Implementation_Requirements/13_API-Security

URL_MATERIAL_SECHEADER: https://secodis.github.io/TSS-WEB/D_Material/Requirements_for_HTTP_Header_Security
URL_MATERIAL_TOPTENMAPPING: https://secodis.github.io/TSS-WEB/D_Material/OWASP_Top_Ten_Mapping
URL_MATERIAL_SAMMMAPPING: https://secodis.github.io/TSS-WEB/D_Material/OWASP_SAMM-2.0-Mapping

URL_MATERIAL_TSSWEBOLD: https://secodis.atlassian.net/wiki/spaces/TSSWEB

URL_OWASPTOPTEN: https://owasp.org/www-project-top-ten/
URL_OWASPSAMM: https://owaspsamm.org/model/
URL_IEC27002: https://www.iso.org/standard/2700
URL_NISTSSDF: https://csrc.nist.gov/Projects/ssdf
URL_SAFECODESSDLC: https://safecode.org/resource-secure-development-practices/fundamental-practices-secure-software-development-2/
