name: Inject Variables into GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  inject-variables:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Repository Variables
      id: vars
      run: |
        git config --list > variables.txt
        cat variables.txt

    - name: Inject Variables into Markdown Files
      run: |
        while read -r line; do
          key=$(echo $line | cut -d'=' -f1 | sed 's/\./_/g')
          value=$(echo $line | cut -d'=' -f2- | sed 's/[\/&]/\\&/g')
          find . -type f -name "*.md" -exec sed -i "s/{{${key}}}/${value}/g" {} +
        done < variables.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update variables in Markdown files"
        git push
